### PR TITLE
Implement support for parallel builds

### PR DESCRIPTION
**Pull request by CyberShadow**
~~Untested.~~

Seems to work: https://coveralls.io/builds/26943546

### CODE REVIEW

**Comment by sviridov** [comment]
Hi @CyberShadow, thank you for opening all these pull requests!
Unfortunately, I have no interest in maintaining this project, so I would happily pass this duty to somebody else.
It looks like you made yourself quite familiar with the codebase so far. Are you interested in becoming a maintainer of this project?

**Comment by CyberShadow** [comment]
Sure.

We use undercover.el in https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode, which I'm maintaining.

**Comment by sviridov** [comment]
Great news, thank you!

I'm not sure what is the best process to pass maintainer role on Github, so I suggest following plan:

- You create a fork of this repository (if you want it to be different from CyberShadow/undercover.el.)
- I add mention of it to the README file in my version of the repo.
- We update the link to the repo in Melpa https://github.com/melpa/melpa/blob/master/recipes/undercover.

Does this plan sound good for you?

**Comment by CyberShadow** [comment]
Hi,

We could do that, though may I suggest one of the following:

1. Just add me as a collaborator. Then I'll be able to push to the repository and review pull requests. This will preserve existing issues and will not require updating any metadata on MELPA or anywhere else.

2. If you would rather no longer be associated with the project, we could move it to a new organization. This will also preserve issues etc., and moving will create a redirect, so no metadata will need to be updated either.

**Comment by sviridov** [comment]
Hey,

Yes, I prefer option #2. Will you create such an organization? I will be able to move other undercover.el related projects to it as well.

**Comment by CyberShadow** [comment]
OK, done: https://github.com/undercover-el

**Comment by sviridov** [comment]
@CyberShadow, thank you! I have transferred all related repositories under this organization. I hope you have permission to maintain this project now.

**Comment by CyberShadow** [comment]
Looks good, thanks! I will apply my fixes soon.

One thing I should point out is that if you do decide to contribute in the future, you probably want to avoid forking the repositories there back to your account, as that will break the redirect (and then we *will* have to update external metadata etc.). Instead, you can create a branch on undercover-el/undercover.el or just push there directly as before.

**Comment by sviridov** [comment]
Yep, make sense, thank you!

**Pull request merged**
